### ISSUE TITLE
Issues related to tissuepositions$mask[i] <- C57BL10_mask_fliprot[tissuepositions$V6[i], tissuepositions$V5[i]].

### ISSUE THREAD

**Issue by feasiblee** [lauraheezen/SpatialAnalysis_DMD_mice#1]
Hello professor, in the process of reproducing your article, I encountered a question: in the SpatialAnalysis_DMDmousemodels.rmd file about 263 lines of code, can the read PNG image be tissue_lowres_image.png file? 

263 #For-loop (loading and aligning masks to the data) 
for(idx in filenames) {
#idx <- filenames[23]
    C57BL10_mask <- readPNG(source = paste0(idx), native = FALSE, info = TRUE) #Read the masks

After reading, in the for (i in 1:dim(tissuepositions)[1]){
        tissuepositions$mask[i] <- C57BL10_mask_fliprot[tissuepositions$V6[i], tissuepositions$V5[i]]
Error in C57BL10_mask_fliprot[tissuepositions$V6[i], tissuepositions$V5[i] ] : Subscript out of bounds
would appreciate your response.

**Comment by lauraheezen** [comment]
Dear,

Thank you for your interest and reaching out.
This part of the code was used to load manually drawn maps into the Seurat object. In the end we did not use this in our final analysis but I kept the code there so that other people could do the same.
The idea is that you can draw your own mask on top of an H&E image on e.g. a region of interest and then have that loaded into the object so that you can easily 'select' these spots.

The reason why the for-loop does not work for you is because you do not have my specific drawn masks, but as I said we did not use this anymore.
I hope this helps answering your question, if not please reach out again!

Best wishes,
Laura

From: feasiblee ***@***.***>
Sent: zondag 24 september 2023 3:27
To: lauraheezen/SpatialAnalysis_DMD_mice ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [lauraheezen/SpatialAnalysis_DMD_mice] Issues related to tissuepositions$mask[i] <- C57BL10_mask_fliprot[tissuepositions$V6[i], tissuepositions$V5[i]]. (Issue #1)


Hello professor, in the process of reproducing your article, I encountered a question: in the SpatialAnalysis_DMDmousemodels.rmd file about 263 lines of code, can the read PNG image be tissue_lowres_image.png file?

263 #For-loop (loading and aligning masks to the data)
for(idx in filenames) {
#idx <- filenames[23]
C57BL10_mask <- readPNG(source = paste0(idx), native = FALSE, info = TRUE) #Read the masks

After reading, in the for (i in 1:dim(tissuepositions)[1]){
tissuepositions$mask[i] <- C57BL10_mask_fliprot[tissuepositions$V6[i], tissuepositions$V5[i]]
Error in C57BL10_mask_fliprot[tissuepositions$V6[i], tissuepositions$V5[i] ] : Subscript out of bounds
would appreciate your response.

-

**Comment by feasiblee** [comment]
Dear Dr. Laura



Thank you very much for your reply, solved the problem, but then had a new question in the process of reproduction?


&nbsp;In the SpatialAnalysis_DMDmousemodels.rmd file about 507 lines of code：
png(filename = "C:/Users/lgmheezen/OneDrive - LUMC/Ahmed_Laura_Pietro/Deconvolution/Spotlight/Laura/Myh_C57_myh1.png",


In it Myh_C57_myh1.png this file, it seems that it is not found in the available file of the article, is this file in the C57BL10_adata.h5ad file? Would appreciate your response.

&nbsp; &nbsp;&nbsp;






                       
原始邮件
                       
                     

发件人："lauraheezen"< ***@***.*** &gt;;

发件时间：2023/9/26 18:23

收件人："lauraheezen/SpatialAnalysis_DMD_mice"< ***@***.*** &gt;;

抄送人："feasiblee"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [lauraheezen/SpatialAnalysis_DMD_mice] Issues related totissuepositions$mask[i] <- C57BL10_mask_fliprot[tissuepositions$V6[i],tissuepositions$V5[i]]. (Issue #1)




 Dear,
 
 Thank you for your interest and reaching out.
 This part of the code was used to load manually drawn maps into the Seurat object. In the end we did not use this in our final analysis but I kept the code there so that other people could do the same.
 The idea is that you can draw your own mask on top of an H&amp;E image on e.g. a region of interest and then have that loaded into the object so that you can easily 'select' these spots.
 
 The reason why the for-loop does not work for you is because you do not have my specific drawn masks, but as I said we did not use this anymore.
 I hope this helps answering your question, if not please reach out again!
 
 Best wishes,
 Laura
 
 From: feasiblee ***@***.***&gt;
 Sent: zondag 24 september 2023 3:27
 To: lauraheezen/SpatialAnalysis_DMD_mice ***@***.***&gt;
 Cc: Subscribed ***@***.***&gt;
 Subject: [lauraheezen/SpatialAnalysis_DMD_mice] Issues related to tissuepositions$mask[i] <- C57BL10_mask_fliprot[tissuepositions$V6[i], tissuepositions$V5[i]]. (Issue #1)
 
 
 Hello professor, in the process of reproducing your article, I encountered a question: in the SpatialAnalysis_DMDmousemodels.rmd file about 263 lines of code, can the read PNG image be tissue_lowres_image.png file?
 
 263 #For-loop (loading and aligning masks to the data)
 for(idx in filenames) {
 #idx <- filenames[23]
 C57BL10_mask <- readPNG(source = paste0(idx), native = FALSE, info = TRUE) #Read the masks
 
 After reading, in the for (i in 1:dim(tissuepositions)[1]){
 tissuepositions$mask[i] <- C57BL10_mask_fliprot[tissuepositions$V6[i], tissuepositions$V5[i]]
 Error in C57BL10_mask_fliprot[tissuepositions$V6[i], tissuepositions$V5[i] ] : Subscript out of bounds
 would appreciate your response.
 
 -

**Comment by lauraheezen** [comment]
Dear,

Happy to hear that.
Correct, as we as muscle biologists are always interested to see the ‘muscle composition’, so the different fiber types of the muscles we plot the expression of different genes:
Myh1, Myh7, Myh4 and Myh2 for all the different mouse models. We again did not use this in the final paper, but it’s to show how you can look at it.

The specific line you’re referring to is just the way to save a plot as a .png it is thus not “part” of any other data file.
If you were to run these lines yourself you’d need to change the storage location marked in red below for you to save your .png plot of the specific Myh markers.

Hope this helps,
Laura

**Comment by feasiblee** [comment]
Thank you, Dr. Laura, for your reply, much appreciated







                       
原始邮件
                       
                     

发件人："lauraheezen"< ***@***.*** &gt;;

发件时间：2023/9/26 19:40

收件人："lauraheezen/SpatialAnalysis_DMD_mice"< ***@***.*** &gt;;

抄送人："feasiblee"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [lauraheezen/SpatialAnalysis_DMD_mice] Issues related totissuepositions$mask[i] <- C57BL10_mask_fliprot[tissuepositions$V6[i],tissuepositions$V5[i]]. (Issue #1)




 Dear, 
 
 Happy to hear that. 
 Correct, as we as muscle biologists are always interested to see the ‘muscle composition’, so the different fiber types of the muscles we plot the expression of different genes: 
 Myh1, Myh7, Myh4 and Myh2 for all the different mouse models. We again did not use this in the final paper, but it’s to show how you can look at it. 
 
 The specific line you’re referring to is just the way to save a plot as a .png it is thus not “part” of any other data file. 
 If you were to run these lines yourself you’d need to change the storage location marked in red below for you to save your .png plot of the specific Myh markers. 
 
 Hope this helps, 
 Laura

**Comment by feasiblee** [comment]
Dear Dr. Laura
&nbsp; Sorry to interrupt you, in the section "Rename/label the clusters and plot with nice colors", I am curious about the group annotation database you use, I annotated by finding out that cellmarker2 was used, in the process of commenting, I feel a little confused, hope to receive your reply, thank you.
&nbsp;
tian
                       
原始邮件
                       
                     

发件人："lauraheezen"< ***@***.*** &gt;;

发件时间：2023/9/26 19:40

收件人："lauraheezen/SpatialAnalysis_DMD_mice"< ***@***.*** &gt;;

抄送人："feasiblee"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [lauraheezen/SpatialAnalysis_DMD_mice] Issues related totissuepositions$mask[i] <- C57BL10_mask_fliprot[tissuepositions$V6[i],tissuepositions$V5[i]]. (Issue #1)




 Dear, 
 
 Happy to hear that. 
 Correct, as we as muscle biologists are always interested to see the ‘muscle composition’, so the different fiber types of the muscles we plot the expression of different genes: 
 Myh1, Myh7, Myh4 and Myh2 for all the different mouse models. We again did not use this in the final paper, but it’s to show how you can look at it. 
 
 The specific line you’re referring to is just the way to save a plot as a .png it is thus not “part” of any other data file. 
 If you were to run these lines yourself you’d need to change the storage location marked in red below for you to save your .png plot of the specific Myh markers. 
 
 Hope this helps, 
 Laura

**Comment by feasiblee** [comment]
Dear Dr. Laura



My own carelessness did not read carefully, but just now I saw the specific group annotation operation in your paper, the problem has been solved, thank you.



tian






                       
原始邮件
                       
                     

发件人："lauraheezen"< ***@***.*** &gt;;

发件时间：2023/9/26 19:40

收件人："lauraheezen/SpatialAnalysis_DMD_mice"< ***@***.*** &gt;;

抄送人："feasiblee"< ***@***.*** &gt;;"Author"< ***@***.*** &gt;;

主题：Re: [lauraheezen/SpatialAnalysis_DMD_mice] Issues related totissuepositions$mask[i] <- C57BL10_mask_fliprot[tissuepositions$V6[i],tissuepositions$V5[i]]. (Issue #1)




 Dear, 
 
 Happy to hear that. 
 Correct, as we as muscle biologists are always interested to see the ‘muscle composition’, so the different fiber types of the muscles we plot the expression of different genes: 
 Myh1, Myh7, Myh4 and Myh2 for all the different mouse models. We again did not use this in the final paper, but it’s to show how you can look at it. 
 
 The specific line you’re referring to is just the way to save a plot as a .png it is thus not “part” of any other data file. 
 If you were to run these lines yourself you’d need to change the storage location marked in red below for you to save your .png plot of the specific Myh markers. 
 
 Hope this helps, 
 Laura
